steps:

# Mock Image Facade

- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './imagefacade_os', './cmd/imagefacadeos/imagefacade_os.go']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor-oc-imagefacade'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-if-ex:$BRANCH_NAME', './']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-if-ex:$BRANCH_NAME']
